language: scala

scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
script:
  - sbt "++ $TRAVIS_SCALA_VERSION test"

sudo: false

jdk: openjdk8

services:
  - postgresql

addons:
  postgresql: '9.4'

before_script:
  - sbt scalafmtCheckAll || { echo "[error] Unformatted code found. Please run 'scalafmtAll' and commit the reformatted code."; false; }
  - sbt scalafmtSbtCheck || { echo "[error] Unformatted sbt code found. Please run 'scalafmtSbt' and commit the reformatted code."; false; }
  - psql -c 'create database akkapg;' -U postgres
  - psql akkapg -c "create extension hstore;" -U postgres
  - psql -c "create user akkapg with password 'akkapg';" -U postgres
  - psql -c "grant all privileges on database akkapg to akkapg;" -U postgres

cache:
  directories:
    - "$HOME/.ivy2"
    - "$HOME/.sbt"